### ISSUE TITLE
Bogota no es departamento

### ISSUE THREAD

**Issue by blueminded** [saulmoralespa/departamentos-y-ciudades-de-colombia-para-woocommerce#1]
Hola, 

Muy buen plugin, el único de detalle es que Bogota esta como si fuera un departamento y en realidad es una ciudad de Cundinamarca.

**Comment by saulmoralespa** [comment]
Ya esta retirado

**Comment by lilarock3rs** [comment]
Hola, esto sigue pasando... Aparece Bogotá como departamento.
Muchas gracias
